package mof;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author ana
 */
public class Frame extends javax.swing.JFrame {

    public Frame() {
        initComponents();
        this.setTitle("Match selector");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(480, 360));
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("mof/logo.png")).getImage());
        tabbedpane.addTab("Judges", new JScrollPane(judges));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        addteamTextField = new javax.swing.JTextField();
        addteamButton = new javax.swing.JButton();
        deleteteamButton = new javax.swing.JButton();
        firststatusbarLabel = new javax.swing.JLabel();
        makematchesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addteamTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addteamTextFieldKeyTyped(evt);
            }
        });

        addteamButton.setText("Add new team");
        addteamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addteamButtonActionPerformed(evt);
            }
        });

        deleteteamButton.setText("Delete selected team");
        deleteteamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteteamButtonActionPerformed(evt);
            }
        });

        firststatusbarLabel.setFont(new java.awt.Font("Open Sans", 2, 12)); // NOI18N
        firststatusbarLabel.setText("                   ");

        makematchesButton.setText("Make matches!");
        makematchesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makematchesButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(tabbedpane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addteamTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addteamButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteteamButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(makematchesButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(firststatusbarLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addteamButton)
                    .addComponent(addteamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteteamButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firststatusbarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makematchesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTeam() {
        textareaHash.put(numberOfTeamsPlusOne, new JTextArea());
        tabbedpane.addTab(addteamTextField.getText(), new JScrollPane(textareaHash.get(numberOfTeamsPlusOne)));
        firststatusbarLabel.setText("Team '" + addteamTextField.getText() + "' added.");
        addteamTextField.setText("");
        numberOfTeamsPlusOne++;
    }

    Hashtable<String, Integer> table = new Hashtable<String, Integer>();

    private void addteamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addteamButtonActionPerformed
        addTeam();
    }//GEN-LAST:event_addteamButtonActionPerformed

    private void addteamTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addteamTextFieldKeyTyped
        if (evt.getKeyChar() == '\n') {
            addTeam();
        }
    }//GEN-LAST:event_addteamTextFieldKeyTyped

    private void makematchesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makematchesButtonActionPerformed
        String[] s = judges.getText().split("\\r?\\n");
        Judge[] j = new Judge[s.length];
        for (int i = 0; i < s.length; i++) {
            j[i] = new Judge(s[i]);
        }
        judgesArrayList = new ArrayList<>(Arrays.asList(j));

        Team[] t = new Team[numberOfTeamsPlusOne - 1];
        for (int i = 1; i < numberOfTeamsPlusOne; i++) {
            t[i - 1] = new Team(textareaHash.get(i).getText().split("\\r?\\n"));
        }
        teamsArrayList = new ArrayList<>(Arrays.asList(t));

        jTextArea1.setText("Number of teams plus one for the judges: " + String.valueOf(numberOfTeamsPlusOne)
                + '\n' + "Array list consisting of the judges:" + String.valueOf(judgesArrayList) + '\n'
        + "Array list consisting of the teams:" + String.valueOf(teamsArrayList));
    }//GEN-LAST:event_makematchesButtonActionPerformed

    private void deleteteamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteteamButtonActionPerformed
        for (int i = 0; i < tabbedpane.getTabCount(); i++) {
            if (tabbedpane.getComponentAt(i).isShowing()) {
                if (i > 0) {
                    firststatusbarLabel.setText("Team '" + tabbedpane.getTitleAt(i) + "' deleted.");
                    tabbedpane.remove(i);
                    numberOfTeamsPlusOne--;
                } else {
                    firststatusbarLabel.setText("Can't delete the judges!");

                }
                break;
            }
        }
    }//GEN-LAST:event_deleteteamButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException |
                InstantiationException |
                IllegalAccessException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //<editor-fold defaultstate="collapsed" desc=" Create and display the form ">
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame().setVisible(true);
        });
        //</editor-fold>
    }

    final private JTextPane judges = new JTextPane();
    private ArrayList<Judge> judgesArrayList;
    private Hashtable<Integer, JTextArea> textareaHash = new Hashtable<Integer, JTextArea>();
    private ArrayList<Team> teamsArrayList;
    private int numberOfTeamsPlusOne = 1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addteamButton;
    private javax.swing.JTextField addteamTextField;
    private javax.swing.JButton deleteteamButton;
    private javax.swing.JLabel firststatusbarLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton makematchesButton;
    private javax.swing.JTabbedPane tabbedpane;
    // End of variables declaration//GEN-END:variables
}
